Fake news classifier using LSTM

In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("/content/drive/My Drive/Deep learning/train.csv")

In [3]:
data.head()

id  ... label
0   0  ...     1
1   1  ...     0
2   2  ...     1
3   3  ...     1
4   4  ...     1

[5 rows x 5 columns]

In [4]:
df=data.dropna() #Dropping NaN values

In [5]:
x=df.drop('label',axis=1)

In [6]:
y=df['label']

In [7]:
x.shape

(18285, 4)

In [9]:
y.shape

(18285,)

In [10]:
import tensorflow as tf

In [11]:
tf.__version__

'2.2.0'

In [12]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Bidirectional


In [13]:
voc_size=5000

One Hot Encoding


In [14]:
message=x.copy()

In [15]:
message['title'][0]

'House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted It'

In [16]:
message.reset_index(inplace=True)

In [17]:
import nltk
import re

In [18]:
from nltk.corpus import stopwords

In [19]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

Data Preprocessing

In [20]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
corpus=[]
for i in range(0,len(message)):
  print(i)
  review=re.sub('[^a-zA-Z]',' ',message['title'][i])
  review=review.lower()
  review=review.split()
  review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
  review=' '.join(review)
  corpus.append(review)

Streaming output truncated to the last 5000 lines.
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
13443
1

In [21]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [22]:
one_hot_rep=[one_hot(words,voc_size) for words in corpus]

In [23]:
print(one_hot_rep)

[[4610, 2719, 4744, 1431, 1178, 3523, 4701, 4046, 450, 4220], [82, 1322, 1279, 2225, 2206, 1806, 972], [2523, 3130, 4267, 3172], [720, 3239, 3388, 2215, 4981, 1296], [896, 2206, 4914, 929, 1509, 502, 2206, 3560, 1396, 2189], [1684, 1936, 4992, 4629, 1729, 1192, 4230, 3821, 2549, 2595, 3032, 4030, 764, 3539, 972], [433, 2075, 627, 471, 841, 1751, 177, 513, 1964, 2288, 345], [3572, 2014, 1105, 3542, 1290, 1452, 1192, 2301, 1964, 2288, 345], [2087, 2303, 2755, 2591, 4078, 1133, 4960, 4257, 1192, 1824], [3849, 1480, 1978, 4291, 250, 1999, 322, 4807], [3156, 3999, 4632, 548, 1969, 1903, 3035, 3775, 1261, 3427, 4594], [2215, 2487, 1178, 1133, 1192, 1290], [4813, 2286, 1007, 1329, 383, 346, 2662, 1433, 3029], [1820, 2670, 3792, 1465, 2616, 1047, 2952, 1964, 2288, 345], [3453, 1089, 3082, 2055, 387, 1964, 2288, 345], [735, 4757, 2811, 950, 3678, 2123, 4694, 2002, 895, 3445], [4867, 2355, 1322], [1869, 958, 251, 589, 1192, 3346, 3864, 972], [4712, 4006, 1279, 2004, 3511, 3302, 3940, 169, 502], 

Embedding Representation


In [24]:
sen_length=20
emb_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sen_length)
print(emb_docs)

[[   0    0    0 ... 4046  450 4220]
 [   0    0    0 ... 2206 1806  972]
 [   0    0    0 ... 3130 4267 3172]
 ...
 [   0    0    0 ... 1964 2288  345]
 [   0    0    0 ...  299 1486 4187]
 [   0    0    0 ... 2071 3320 3408]]


Model_Building

In [25]:
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sen_length))
model.add(Bidirectional(LSTM(100)))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 40)            200000    
_________________________________________________________________
bidirectional (Bidirectional (None, 200)               112800    
_________________________________________________________________
dense (Dense)                (None, 1)                 201       
Total params: 313,001
Trainable params: 313,001
Non-trainable params: 0
_________________________________________________________________
None


In [26]:
import numpy as np
X_final=np.array(emb_docs)
y_final=np.array(y)

In [27]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [29]:
#Model Training

model.fit(X_train,y_train,validation_data=(X_test,y_test),batch_size=64,epochs=10)

Epoch 1/10
192/192 [==============================] - 5s 24ms/step - loss: 0.2967 - accuracy: 0.8557 - val_loss: 0.1941 - val_accuracy: 0.9229
Epoch 2/10
192/192 [==============================] - 4s 20ms/step - loss: 0.1325 - accuracy: 0.9496 - val_loss: 0.2015 - val_accuracy: 0.9234
Epoch 3/10
192/192 [==============================] - 4s 20ms/step - loss: 0.0866 - accuracy: 0.9693 - val_loss: 0.2226 - val_accuracy: 0.9193
Epoch 4/10
192/192 [==============================] - 4s 20ms/step - loss: 0.0658 - accuracy: 0.9789 - val_loss: 0.2348 - val_accuracy: 0.9198
Epoch 5/10
192/192 [==============================] - 4s 20ms/step - loss: 0.0459 - accuracy: 0.9844 - val_loss: 0.3459 - val_accuracy: 0.9102
Epoch 6/10
192/192 [==============================] - 4s 20ms/step - loss: 0.0316 - accuracy: 0.9900 - val_loss: 0.3392 - val_accuracy: 0.9140
Epoch 7/10
192/192 [==============================] - 4s 20ms/step - loss: 0.0211 - accuracy: 0.9936 - val_loss: 0.4713 - val_accuracy: 0.9110

In [30]:
#Performance measure:
y_pred=model.predict_classes(X_test)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


In [31]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.93      0.91      0.92      3419
           1       0.89      0.91      0.90      2616

    accuracy                           0.91      6035
   macro avg       0.91      0.91      0.91      6035
weighted avg       0.91      0.91      0.91      6035



In [32]:
print(confusion_matrix(y_test,y_pred))

[[3121  298]
 [ 234 2382]]


In [33]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.911847555923778


Adding Droput Layer

In [34]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model1=Sequential()
model1.add(Embedding(voc_size,embedding_vector_features,input_length=sen_length))
model1.add(Dropout(0.3))
model1.add(Bidirectional(LSTM(100)))
model1.add(Dropout(0.3))
model1.add(Dense(1,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [35]:
model1.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 5s 24ms/step - loss: 0.3277 - accuracy: 0.8472 - val_loss: 0.1980 - val_accuracy: 0.9190
Epoch 2/10
192/192 [==============================] - 4s 20ms/step - loss: 0.1502 - accuracy: 0.9406 - val_loss: 0.1924 - val_accuracy: 0.9218
Epoch 3/10
192/192 [==============================] - 4s 20ms/step - loss: 0.1068 - accuracy: 0.9592 - val_loss: 0.1992 - val_accuracy: 0.9211
Epoch 4/10
192/192 [==============================] - 4s 20ms/step - loss: 0.0775 - accuracy: 0.9730 - val_loss: 0.2393 - val_accuracy: 0.9216
Epoch 5/10
192/192 [==============================] - 4s 20ms/step - loss: 0.0577 - accuracy: 0.9803 - val_loss: 0.2653 - val_accuracy: 0.9183
Epoch 6/10
192/192 [==============================] - 4s 20ms/step - loss: 0.0435 - accuracy: 0.9858 - val_loss: 0.3268 - val_accuracy: 0.9133
Epoch 7/10
192/192 [==============================] - 4s 20ms/step - loss: 0.0333 - accuracy: 0.9887 - val_loss: 0.3871 - val_accuracy: 0.9130

In [36]:
y_pred1=model1.predict_classes(X_test)

In [37]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print(classification_report(y_test,y_pred1))
print(confusion_matrix(y_test,y_pred1))
print(accuracy_score(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.94      0.91      0.92      3419
           1       0.89      0.92      0.90      2616

    accuracy                           0.91      6035
   macro avg       0.91      0.92      0.91      6035
weighted avg       0.92      0.91      0.91      6035

[[3113  306]
 [ 209 2407]]
0.9146644573322287
